### ISSUE TITLE
server umask not applied when uploading files

### ISSUE THREAD

**Issue by rosch100** [superflexible/TGPuttyLib#2] opened 2019-12-03 12:10 UTC
When I transfer files, they seem to have random permissions, e.g.:
```
user@nfs:~$ ls -la README.md 
---------- 1 user user 2053 Dez  3 09:28 README.md
```
Server umask is 0002.
I observed other (sometimes quite strange) permissions as well.
As a workaround, I read the stats of the target directory and assign the permissions to the transferred file. It seems to be quite awkward to having to do it this way:
```
sftp.GetStat('.', Attrs);
sftp.UploadFile(MyFile, False);
sftp.GetStat(MyFile, AttrsUpload);
AttrsUpload.permissions := Attrs.permissions;
sftp.SetStat(MyFile, AttrsUpload);
```
Is there a better way to achieve proper permissions of the uploaded files?

**Comment by superflexible** [comment] 2019-12-03 14:34
Many thanks, I will look into this today.

**Comment by superflexible** [comment] 2019-12-03 16:40
Hello,
it may not be related, but could you let me know if you are using the class TTGPuttySFTP or the Delphi component class TTGPuttySFTPClient?

**Comment by rosch100** [comment] 2019-12-03 16:46
I'm using TTGPuttySFTPClient. Btw, since TTGPuttySFTPClient is using tgputtysftp.pas, there are quite a few implicit AnsiString to string conversions. You see it, when you turn on the warnings.

**Comment by superflexible** [comment] 2019-12-03 16:55
Hi,
thanks for the info, I will fix the warnings.

I think Putty does not send any user permissions at all, so the SFTP server should use its default permissions. Can you let me know what server it is? Also I think you should compare the behavior against psftp.exe from Putty as well as FileZilla. Theoretically, TGPuttyLib should behave identical to psftp.exe.

**Comment by rosch100** [comment] 2019-12-03 17:27
Just checked with psftp and the permissions on the server side are correct. The ssh server running is:
```
dpkg --list | grep openssh
ii  openssh-client                        1:7.6p1-4ubuntu0.3                              amd64        secure shell (SSH) client, for secure access to remote machines
ii  openssh-server                        1:7.6p1-4ubuntu0.3                              amd64        secure shell (SSH) server, for secure access from remote machines
ii  openssh-sftp-server                   1:7.6p1-4ubuntu0.3                              amd64        secure shell (SSH) sftp server module, for SFTP access from remote machines
```

**Comment by superflexible** [comment] 2019-12-03 17:48
Hi,
many thanks, I can confirm the problem now. It seems to happen because the UploadFile function opens a Delphi stream and uploads from that, rather than passing a local file name to the Putty DLL. I implemented it like that to avoid any Unicode problems with local filenames, and because my application needs to be able to upload directly from streams anyway. The Delphi stream can be used because the DLL uses a callback function to fill its upload buffer. 

In any case, it can't be that hard to find the bug, I will fix it.

**Comment by superflexible** [comment] 2019-12-03 18:03
Found it. In psftp.c, I missed the fact that open_existing_file sets permissions to -1.

So when not calling open_existing_file, because we are uploading via callback from a Delphi stream, the local permissions variable has to be set to -1 too.

I am uploading the fixed files now.

**Comment by superflexible** [comment] 2019-12-03 18:24
I have pushed the fixes, you need an updated tgputtylib.dll because the bug was in the DLL.

**Comment by superflexible** [comment] 2019-12-03 22:10
I have now fixed the warnings too.

**Comment by superflexible** [comment] 2019-12-04 19:43
Closing this now ...

**Closed by superflexible** 2019-12-04 19:43 UTC
